'use server';
import { revalidatePath } from 'next/cache'; import { redirect } from 'next/navigation'; import { requireAdmin } from '@/lib/auth';
const allowed=['image/jpeg','image/png','image/webp']; const max=5*1024*1024;
const slugify=(v:string)=>v.toLowerCase().trim().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'');
async function imageUrl(supabase: Awaited<ReturnType<typeof requireAdmin>>['supabase'], file: File, oldUrl?:string|null) { if(!file.size)return oldUrl??null; if(!allowed.includes(file.type)||file.size>max)throw new Error('Image must be JPG, PNG, or WEBP and no larger than 5 MB.'); const ext=file.type.split('/')[1]; const path=`products/${crypto.randomUUID()}.${ext}`; const {error}=await supabase.storage.from('product-images').upload(path,file,{contentType:file.type,upsert:false}); if(error)throw new Error(error.message); const {data}=supabase.storage.from('product-images').getPublicUrl(path); if(oldUrl){const marker='/product-images/';const oldPath=oldUrl.split(marker)[1]?.split('?')[0];if(oldPath)await supabase.storage.from('product-images').remove([oldPath]);} return data.publicUrl; }
function fields(form:FormData){const name=String(form.get('name')||'').trim(),brand=String(form.get('brand')||'').trim(),category_id=String(form.get('category_id')||''),description=String(form.get('description')||'').trim(),affiliate_url=String(form.get('affiliate_url')||'').trim(),affiliate_platform=String(form.get('affiliate_platform')||'website'),status=String(form.get('status')||'draft'); if(!name||!brand||!category_id||!affiliate_url)throw new Error('Please complete all required fields.'); let url:URL;try{url=new URL(affiliate_url)}catch{throw new Error('Affiliate URL must be a valid URL.')}if(!['http:','https:'].includes(url.protocol))throw new Error('Affiliate URL must use HTTP or HTTPS.'); if(!['draft','published','archived'].includes(status))throw new Error('Invalid status.'); return {name,slug:slugify(name),brand,category_id,description:description||null,affiliate_url,affiliate_platform,featured:form.get('featured')==='on',status};}
export async function saveProduct(form:FormData){const {supabase}=await requireAdmin(); const payload=fields(form); const file=form.get('image'); const url=file instanceof File?await imageUrl(supabase,file):null; const {error}=await supabase.from('products').insert({...payload,image_url:url});if(error)throw new Error(error.message);revalidatePath('/');redirect('/admin/products');}
export async function updateProduct(id:string,oldUrl:string|null,form:FormData){const {supabase}=await requireAdmin();const payload=fields(form);const file=form.get('image');const image_url=file instanceof File?await imageUrl(supabase,file,oldUrl):oldUrl;const {error}=await supabase.from('products').update({...payload,image_url}).eq('id',id);if(error)throw new Error(error.message);revalidatePath('/');redirect('/admin/products');}
export async function archiveProduct(id:string){const {supabase}=await requireAdmin();await supabase.from('products').update({status:'archived'}).eq('id',id);revalidatePath('/');revalidatePath('/admin/products');}
export async function saveCategory(form:FormData){const {supabase}=await requireAdmin();const name=String(form.get('name')||'').trim();if(!name)throw new Error('Category name is required.');const {error}=await supabase.from('categories').insert({name,slug:slugify(name),description:String(form.get('description')||'').trim()||null});if(error)throw new Error(error.message);revalidatePath('/');revalidatePath('/admin/categories');}
export async function archiveCategory(id:string){const {supabase}=await requireAdmin();await supabase.from('categories').update({archived:true}).eq('id',id);revalidatePath('/');revalidatePath('/admin/categories');}
export async function signOut(){const {supabase}=await requireAdmin();await supabase.auth.signOut();redirect('/');}
